spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/secondsecurityserver
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: true


jwt:
  public:
    key: classpath:/key/app.pub
  private:
    key: classpath:/key/app.key

server:
  port: 8080
  address: localhost